### ISSUE TITLE
change hard-coded driving_variant_label (r0i0p0f0) for invariant variables 

### ISSUE THREAD

**Issue by gnikulin** [doblerone/HCLIM2CMOR#16]
Currently, `driving_variant_label` for invariant fields  is hard-coded in tools.py as `r0i0p0f0`, similar to CORDEX-CMIP5. The new CORDEX-CMIP6 specs define that  

"For all invariant fields (frequency = fx, e.g. orog or sftlf), driving_variant_label must be the same as variant_label of the driving CMIP6 simulation (e.g. r1i1p1f1, r2i1p1f1, etc.); r0i0p0f0 is not allowed."

We need simply to delete the hard-coded value `r0i0p0f0`.

**Comment by ljoakim** [comment]
adding participants @doblerone @ljoakim
